# Generated by Django 4.2.4 on 2025-09-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
