# Generated by Django 4.2.4 on 2025-09-28 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0003_categoria_tipo'),
        ('servicio', '0004_alter_servicio_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='categoria.categoria'),
            preserve_default=False,
        ),
    ]
