# Generated by Django 4.2.4 on 2025-10-01 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0004_alter_categoria_tipo'),
        ('sucursal', '0004_remove_sucursal_latitud_remove_sucursal_longitud'),
        ('servicio', '0005_servicio_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='sucursal.sucursal'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='categoria.categoria'),
        ),
    ]
