# Generated by Django 4.2.4 on 2025-10-02 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0006_servicio_sucursal_alter_servicio_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='sucursal',
        ),
    ]
