# Generated by Django 5.2.10 on 2026-03-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='cargo',
            field=models.CharField(blank=True, choices=[('lavanderia', 'Lavandería'), ('gomeria', 'Gomería'), ('electricidad', 'Electricidad'), ('chapa_pintura', 'Chapa y Pintura')], max_length=30, null=True),
        ),
    ]
