# Generated by Django 4.2.4 on 2026-03-13 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sucursal', '0001_initial'),
        ('user', '0002_alter_empleado_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='sucursal.sucursal'),
        ),
    ]
