# Generated by Django 4.2.4 on 2025-09-29 14:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0004_alter_categoria_tipo'),
        ('user', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(default='Desconocido', max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('tipo', models.CharField(default='Otro', max_length=100)),
                ('anio_fabricacion', models.PositiveIntegerField(default=2000)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos', to='categoria.categoria')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.cliente')),
            ],
            options={
                'verbose_name': 'vehiculo',
                'verbose_name_plural': 'vehiculos',
                'db_table': 'vehiculo',
            },
        ),
    ]
