# Generated by Django 4.2.4 on 2026-01-08 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
        ('carrito', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritoitem',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producto.producto'),
        ),
    ]
