# Generated by Django 4.2.4 on 2025-09-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('producto', 'Producto'), ('servicio', 'Servicio')], default='producto', max_length=20),
        ),
    ]
