# Generated by Django 4.2.4 on 2025-09-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0003_categoria_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('producto', 'Producto'), ('servicio', 'Servicio'), ('vehiculo', 'Vehiculo')], default='producto', max_length=20),
        ),
    ]
