# Generated by Django 4.2.4 on 2025-10-17 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(default='', max_length=20)),
                ('ciudad', models.CharField(blank=True, default='', max_length=100)),
                ('provincia', models.CharField(blank=True, default='', max_length=100)),
                ('servicios', models.ManyToManyField(blank=True, related_name='sucursales', to='servicio.servicio')),
            ],
            options={
                'verbose_name': 'sucursal',
                'verbose_name_plural': 'sucursales',
                'db_table': 'sucursal',
            },
        ),
    ]
