# Generated by Django 4.2.4 on 2025-09-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursal', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='ciudad',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='provincia',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
