# Generated by Django 4.2.4 on 2025-10-01 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sucursal', '0003_sucursal_ciudad_sucursal_provincia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sucursal',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='sucursal',
            name='longitud',
        ),
    ]
