# Generated by Django 4.2.4 on 2025-10-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0007_remove_servicio_sucursal'),
        ('sucursal', '0006_alter_sucursal_servicios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='servicios',
            field=models.ManyToManyField(related_name='sucursales', to='servicio.servicio'),
        ),
    ]
