# Generated by Django 4.2.4 on 2025-11-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta_detalle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventadetalle',
            name='descuento',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ventadetalle',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
