# Generated by Django 4.2.4 on 2026-01-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta_detalle', '0002_alter_ventadetalle_descuento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventadetalle',
            name='descuento',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
