# Generated by Django 4.2.4 on 2025-10-01 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0006_servicio_sucursal_alter_servicio_categoria'),
        ('turno', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='servicio.servicio'),
        ),
    ]
