# Generated by Django 4.2.4 on 2025-10-02 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turno', '0003_turno_servicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='servicio',
        ),
    ]
