# Generated by Django 4.2.4 on 2025-10-26 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reserva', '0001_initial'),
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehiculo.vehiculo'),
        ),
    ]
