# Generated by Django 4.2.4 on 2025-10-02 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sucursal', '0005_sucursal_servicios'),
        ('reserva', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sucursal.sucursal'),
        ),
    ]
