# Generated by Django 4.2.4 on 2025-10-10 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turno', '0004_remove_turno_servicio'),
        ('reserva', '0003_reserva_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='turno.turno'),
        ),
    ]
